//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScintillaNET_FindReplaceDialog.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScintillaNET_FindReplaceDialog.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Clock {
            get {
                object obj = ResourceManager.GetObject("Clock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DeleteHS {
            get {
                object obj = ResourceManager.GetObject("DeleteHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line {0}: .
        /// </summary>
        internal static string FindAllResults_ResultsLinePrefix {
            get {
                return ResourceManager.GetString("FindAllResults_ResultsLinePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in Regular Expression: .
        /// </summary>
        internal static string FindReplace_Status_ErrorInRegex {
            get {
                return ResourceManager.GetString("FindReplace_Status_ErrorInRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match could not be found.
        /// </summary>
        internal static string FindReplace_Status_MatchNotFound {
            get {
                return ResourceManager.GetString("FindReplace_Status_MatchNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search match wrapped to the beginning of the document.
        /// </summary>
        internal static string FindReplace_Status_MatchWrappedBeginningDocument {
            get {
                return ResourceManager.GetString("FindReplace_Status_MatchWrappedBeginningDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search match wrapped to the beginning of the selection.
        /// </summary>
        internal static string FindReplace_Status_MatchWrappedBeginningSelection {
            get {
                return ResourceManager.GetString("FindReplace_Status_MatchWrappedBeginningSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search match wrapped to the end of the document.
        /// </summary>
        internal static string FindReplace_Status_MatchWrappedEndDocument {
            get {
                return ResourceManager.GetString("FindReplace_Status_MatchWrappedEndDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search match wrapped to the end of the selection.
        /// </summary>
        internal static string FindReplace_Status_MatchWrappedEndSelection {
            get {
                return ResourceManager.GetString("FindReplace_Status_MatchWrappedEndSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total found: .
        /// </summary>
        internal static string FindReplace_Status_TotalFound {
            get {
                return ResourceManager.GetString("FindReplace_Status_TotalFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total replaced: .
        /// </summary>
        internal static string FindReplace_Status_TotalReplaced {
            get {
                return ResourceManager.GetString("FindReplace_Status_TotalReplaced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to line # must be greater than 0 and less than {0}.
        /// </summary>
        internal static string GoTo_Error_MustBeInRange {
            get {
                return ResourceManager.GetString("GoTo_Error_MustBeInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to line # must be a numeric value.
        /// </summary>
        internal static string GoTo_Error_MustBeNumeric {
            get {
                return ResourceManager.GetString("GoTo_Error_MustBeNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GoToNextMessage {
            get {
                object obj = ResourceManager.GetObject("GoToNextMessage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GoToPreviousMessage {
            get {
                object obj = ResourceManager.GetObject("GoToPreviousMessage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LineColorHS {
            get {
                object obj = ResourceManager.GetObject("LineColorHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
